### ISSUE TITLE
[BUG] Client Site Page:  InstantiateDefaultWebPart of type List returns Null

### ISSUE THREAD

**Issue by matsla** [pnp/PnP-Sites-Core#2781] opened 2020-09-29 09:20 UTC
When try to InstantiateDefaultWebPart with DefaultClientSideWebParts.List it returns NULL. When try InstantiateDefaultWebPart with DefaultClientSideWebParts.NewsFeed it works fine. I have tried different versions of PnP but still same issues, this has previosly been working without any issues. 

We have a lot of custom solutions depending of this functionallity and its very import to have this issue corrected. We have now this issue on 5 different tenants.

      var authManager = new OfficeDevPnP.Core.AuthenticationManager();

      ClientContext ctx = authManager.GetSharePointOnlineAuthenticatedContextTenant(
        "https://xxx.sharepoint.com",
        "XXX",
        "YYY");

      Web web = ctx.Web;
      ctx.Load(web);
      ctx.ExecuteQueryRetry();

      string welcomePagePath = web.WelcomePage;

      string[] welcomePathParts = welcomePagePath.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
      var welcomePageName = welcomePathParts[welcomePathParts.Length - 1];
      var page = web.LoadClientSidePage(welcomePageName);

       
      var listWebPart = page.InstantiateDefaultWebPart(DefaultClientSideWebParts.List);

      listWebPart == NULL

       var components = page.AvailableClientSideComponents();

      // get default List WebPart => f92bf067-bc19-489e-a556-7fe95f508720
      var defaultListWebPart = components.Where(s => s.ComponentType == 1 && s.Name == "f92bf067-bc19-489e-a556-7fe95f508720").FirstOrDefault();

      defaultListWebPart == NULL

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

SharePointPnPCoreOnline 3.25.2009.1 and 3.22.2006.2

**Comment by adzero** [comment] 2020-09-29 09:45
I'm experiencing issues that seems related using the **[PnP-PowerShell module](https://github.com/pnp/PnP-PowerShell)**. 

Applying a template with [`Apply-PnPProvisioningTemplate`](https://docs.microsoft.com/fr-fr/powershell/module/sharepoint-pnp/apply-pnpprovisioningtemplate?view=sharepoint-ps) fails to create list webpart on pages included in template.
Trying to add a list WebPart to a page with [`Add-PnPClientSideWebPart`](https://docs.microsoft.com/fr-fr/powershell/module/sharepoint-pnp/add-pnpclientsidewebpart?view=sharepoint-ps) fails with a Null reference exception. I submitted an [issue](https://github.com/pnp/PnP-PowerShell/issues/2937) for this one in the PnP-Powershell project.

It's critical as our site creation automation processes can't create new valid templated sites anymore.

**Comment by jansenbe** [comment] 2020-09-29 11:30
Duplicate of #2779

**Comment by bmoyer23** [comment] 2020-09-29 15:14
We are also now having issues with Apply-PnPProvisioningTemplate. Our new sites created from template no longer include the list web parts on the site pages. This worked 2 days ago

**Comment by jansenbe** [comment] 2020-09-29 17:32
the underlying issue as described in #2779 is preventing any list web part provisionning, being it via the API, via provisioning engine or via page transformation. Engineering is looking into the root cause right now

**Comment by matsla** [comment] 2020-09-30 05:55
@jansenbe any updates from engineering when this issues will be corrected? Is there any workarounds to temporary solve this issue?

**Comment by Ganesh-Rajagopal** [comment] 2020-09-30 07:21
**@jansenbe** - our server does not have an internet connection using the old version of PnP Powershell SharePoint Online even though we are getting "Null Value" issue while adding "Add-PnPClientSideWebPart"

Kindly answer that how the old version also throwing an error when it is no upgraded to a newer version.

**Comment by dev-a11y** [comment] 2020-09-30 11:37
same for us, looks like not related to pnp engine (we have not upgraded it for almost a year); on our tenant the issue started this week, all our newly provisioned pages are missing list webparts - ughh

**Comment by jansenbe** [comment] 2020-09-30 18:21
The root cause of the problem has been found and a fix is rolling out soon.

**Comment by matsla** [comment] 2020-10-01 06:16
@jansenbe seems to be working now for one of our customer tenants 👍

**Comment by jansenbe** [comment] 2020-10-01 07:38
Think we can close, there's many independent confirmations the issue is fixed

**Closed by jansenbe** 2020-10-01 07:38 UTC
Labels: Needs: Triage :mag:

**Comment by Ganesh-Rajagopal** [comment] 2020-10-01 09:03
Thanks a ton - Now it is working like a charm !!

**Comment by bmoyer23** [comment] 2020-10-01 10:45
thanks. Its working again
