### ISSUE TITLE
[BUG] Add-PnPClientSideWebPart not working for DefaultClientSideWebParts.List

### ISSUE THREAD

**Issue by ARAZA-URBIS** [pnp/PnP-Sites-Core#2780] opened 2020-09-29 08:12 UTC
Add-PnPClientSideWebPart not working for List web part

$pagename = "HomePage.aspx"

$homePage = Get-PnPClientSidePage -Identity $pagename

Add-PnPClientSideWebPart -Page $homePage -DefaultWebPartType List -Section 1 -Column 1 -WebPartProperties @{"isDocumentLibrary"=$true;"selectedListId"="3cb69d7d-5286-4df6-9aa8-f17885ed3b5c"}

Set-PnPClientSidePage -Identity $homePage -Publish

It is throwing error on Add-PnPClientSideWebPart

**Comment by jansenbe** [comment] 2020-09-29 11:29
duplicate of #2781

**Comment by jansenbe** [comment] 2020-09-30 18:21
The root cause of the problem has been found and a fix is rolling out soon.

**Comment by jansenbe** [comment] 2020-10-01 07:38
Think we can close, there's many independent confirmations the issue is fixed

**Closed by jansenbe** 2020-10-01 07:38 UTC
Labels: Needs: Triage :mag:
