### ISSUE TITLE
Apply-PnPProvisioningTemplate: NullReferenceException when applying Tenant handler

### ISSUE THREAD

**Issue by jsuddsjr** [pnp/PnP-Sites-Core#2613] opened 2020-04-08 04:27 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnPjs - https://github.com/pnp/pnpjs
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

I am trying to apply a SPPKG file and StorageEntities to the site, however I can remove both of these elements and get the same result. I have also tried applying the template to TWO different tenants, with the same result.

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

When applying the Tenant handler, the operation fails.

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

Here's the stack trace.

````
Apply-PnPProvisioningTemplate : Object reference not set to an instance of an object.
At C:\Src\sp-custom-learning\deployment\template\ApplyTemplate.ps1:43 char:9
+         Apply-PnPProvisioningTemplate -Handlers $Handlers -Path $temp ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTem
plateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser)
   at SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate.ExecuteCmdlet()
   at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()

````

Here's the salient part of the provisioning template. All the remaining handlers work as expected. Again, the `<pnp:Tenant>` container can be completely empty, and I still get the exception. I am running this through PowerShell, but after looking at their code, it's clearly coming from the engine.

````
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=3.19.2003.0, Culture=neutral, PublicKeyToken=5e633289e95c321a">
    <pnp:Parameters>
      <pnp:Parameter Key="SiteUrl">/sites/M365LP</pnp:Parameter>
    </pnp:Parameters>
  </pnp:Preferences>
  <pnp:Localizations>
    <pnp:Localization LCID="1033" Name="English (United States)" ResourceFile="template.full.en-US.resx" />
    <pnp:Localization LCID="2052" Name="中文(中国)" ResourceFile="template.full.zh-CN.resx" />
    <pnp:Localization LCID="1036" Name="français (France)" ResourceFile="template.full.fr-FR.resx" />
    <pnp:Localization LCID="1031" Name="Deutsch (Deutschland)" ResourceFile="template.full.de-DE.resx" />
    <pnp:Localization LCID="1040" Name="italiano (Italia)" ResourceFile="template.full.it-IT.resx" />
    <pnp:Localization LCID="1041" Name="日本語 (日本)" ResourceFile="template.full.ja-JP.resx" />
    <pnp:Localization LCID="1049" Name="русский (Россия)" ResourceFile="template.full.ru-RU.resx" />
    <pnp:Localization LCID="1046" Name="português (Brasil)" ResourceFile="template.full.pt-BR.resx" />
    <pnp:Localization LCID="3082" Name="español (España, alfabetización internacional)" ResourceFile="template.full.es-ES.resx" />
  </pnp:Localizations>
  <pnp:Tenant>
    <pnp:AppCatalog>
      <pnp:Package Src="customlearning.sppkg" Action="UploadAndPublish" Overwrite="true" />
    </pnp:AppCatalog>
    <pnp:StorageEntities>
      <pnp:StorageEntity Key="MicrosoftCustomLearningCdn" Value="https://pnp.github.io/custom-learning-office-365/learningpathways/" Description="CDN source for Microsoft Content" />
      <pnp:StorageEntity Key="MicrosoftCustomLearningSite" Value="{parameter:SiteUrl}" Description="Custom Learning Site Collection" />
      <pnp:StorageEntity Key="MicrosoftCustomLearningTelemetryOn" Value="true" Description="Custom Learning Telemetry Collection" />
    </pnp:StorageEntities>
  </pnp:Tenant>

````

**Comment by jansenbe** [comment] 2020-04-09 09:29
@jsuddsjr : can you call Get-PnPException immediately after a failed request and provide the output

**Comment by jackpoz** [comment] 2020-06-12 10:35
Trying to apply the template above without having the customlearning.sppkg package throws a null exception
![image](https://user-images.githubusercontent.com/1153754/84493489-1b41c600-aca8-11ea-8f99-7fe8c2054c8c.png)

If I remove the <pnp:Package> element, the template applies without any exception
![image](https://user-images.githubusercontent.com/1153754/84493646-5f34cb00-aca8-11ea-9bdf-8a17bc289469.png)

If I place the sppkg in the same folder, the template applies without any exception
![image](https://user-images.githubusercontent.com/1153754/84493852-c6527f80-aca8-11ea-8e71-802659b0107d.png)

In addition to what @jansenbe mentioned about Get-PnPException, I would suggest also to enable logging with
```powershell
Set-PnPTraceLog -on
```

I will check the null exception in case the file is not found and change that to something more helpful (like an exception with the name of the file not found)

**Comment by jackpoz** [comment] 2020-09-12 14:17
@jsuddsjr could you try again using latest version ? the exception message should be more clear now

**Comment by PaoloPia** [comment] 2020-10-11 16:33
Hi, 
I think that I found the root cause of the issue. It is now fixed in the DEV branch and I will close this item. Thanks for your feedback.

**Closed by PaoloPia** 2020-10-11 16:33 UTC
Labels: Needs: Triage :mag:
